#!/usr/bin/env bash
# Generate Tailwind CSS stylesheet

PROJECT_ROOT="$(git rev-parse --show-toplevel)"
INPUT_FILE="$PROJECT_ROOT/app/assets/tailwindcss/custom.css"
OUTPUT_FILE="$PROJECT_ROOT/app/assets/stylesheets/tailwindcss_custom.css"

tailwindcss-cli build "$INPUT_FILE" -o "$OUTPUT_FILE"
sed -i "1 i\/* This file was generated by the script $(basename "$0"), do not change it manually! */\n" "$OUTPUT_FILE"
